// <auto-generated />
namespace PS2_CisnerosAcostaJoseEnrique.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class secondmigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondmigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "202005220140086_secondmigrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
